@startuml
'https://plantuml.com/sequence-diagram

autonumber

== Start ==

ConcreteAutoOp --> TrajectoryActionBuilder: Build Trajectory
ConcreteAutoOp --> BaseAuto: add sequential actions

== Loop ==
BaseAuto --> PinpointDrive: updatePoseEstimate()
BaseAuto --> BaseAuto: updateRunningActions()
@enduml